### PR TITLE
Fix compilation, enable local proof-of-work fallback

### PR DESCRIPTION
**Pull request by olivereanderson**
# Description of change
The support/v0.4 branch no longer compiles the Rust library due to problems with the specified git dependency on `iota-client`. This PR solves this problem by essentially merging the `wasm-v0.4.3` branch into `support/v0.4`.  

Note: 
- I was not able to figure out exactly why `support/v0.4` cannot keep depending on the previously specified git hash for `iota-client`. Is this important? 
- All crate versions (except `identity-wasm`) have been reverted to `0.4.0` as our CI automatically bumps those when this gets merged.  
- Pinning `iota-crypto` to `0.9.1` is no longer necessary as `0.9.2` has been yanked from crates.io 
 

## Links to any relevant issues
Be sure to reference any related issues by adding `fixes issue #`.

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
Tests run locally. 

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [x] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cycraig** [comment]
Was this requested, is anyone still using the 0.4 version of the Rust library?

> All crate versions (except identity-wasm) have been reverted to 0.4.0 as our CI automatically bumps those when this gets merged.

The CI only bumps them when releasing hotfixes, bumping the `iota-client` version and including the local-PoW fallback are legitimate changes, this is no longer 0.4.0 behaviour.

**Comment by olivereanderson** [comment]
> Was this requested, is anyone still using the 0.4 version of the Rust library? 

This I do not know. @eike-hass  and I thought it might be the case and could be nice for them. 

> The CI only bumps them when releasing hotfixes, bumping the iota-client version and including the local-PoW fallback are legitimate changes, this is no longer 0.4.0 behaviour.

It was my understanding from @eike-hass that this will be bumped to `0.4.1`, but perhaps I misunderstood Eike?

**Comment by eike-hass** [comment]
> > Was this requested, is anyone still using the 0.4 version of the Rust library?
> 
> This I do not know. @eike-hass and I thought it might be the case and could be nice for them.
> 
> > The CI only bumps them when releasing hotfixes, bumping the iota-client version and including the local-PoW fallback are legitimate changes, this is no longer 0.4.0 behaviour.
> 
> It was my understanding from @eike-hass that this will be bumped to `0.4.1`, but perhaps I misunderstood Eike?

At least Wasm `0.4.3` is still the most popular version on npm. I assume until we are on crates we have no real idea how often our rust stuff is included.

**Comment by eike-hass** [comment]
> > The CI only bumps them when releasing hotfixes, bumping the iota-client version and including the local-PoW fallback are legitimate changes, this is no longer 0.4.0 behaviour.
> 
> It was my understanding from @eike-hass that this will be bumped to `0.4.1`, but perhaps I misunderstood Eike?

The version will be bumped automatically when we release the hotfix. I was under the assumption we need the iota client bump to get 0.4 working again?

**Comment by olivereanderson** [comment]
> The version will be bumped automatically when we release the hotfix. I was under the assumption we need the iota client bump to get 0.4 working again?

Yes, we need it. At least I am not able to get `0.4` working without changes to `iota-client` and this was the path of least resistance. If there is a better way then please let me know.

**Review by cycraig — APPROVED** [review]
Not a big fan of performing a hotfix like this since the changelog will probably exclude behaviour changes such as the forced PoW fallback, due to how the changelog generator works (or rather doesn't work) across branches?

We can't even revert to `iota-client 1.1.0` from back then since it was yanked and we have no `Cargo.toml`.

> I was not able to figure out exactly why support/v0.4 cannot keep depending on the previously specified git hash for iota-client. Is this important?

Sounds familiar, I believe it was something to do with a `bee` dependency since back then `iota-client` was pulling from their git repository, not `crates.io`.

**Comment by olivereanderson** [comment]
>what are the implications of only pushing the iota-client dependency change here rather than everything from support/wasm-v0.4, would that break the GitHub Action for hotfixes 

@eike-hass Do you know the answer to this?

**Comment by eike-hass** [comment]
sorry for being dense, but isn't the only relevant change the iota-client update, all the wasm stuff shouldn't matter for people consuming rust.

**Comment by olivereanderson** [comment]
> sorry for being dense, but isn't the only relevant change the iota-client update, all the wasm stuff shouldn't matter for people consuming rust. 

I am fine with only merging the stuff related to the `iota-client` update, but I am not sure one will be able to build working Wasm bindings from this tag then. Does that matter?

**Comment by olivereanderson** [comment]
@eike-hass and @cycraig I have now tried to only bring in the `iota-client` dependency change, but after doing that I was not able to build the bindings anymore. Hence I am wondering if we can just merge this as is?

**Comment by cycraig** [comment]
> Hence I am wondering if we can just merge this as is?

@eike and I discussed this and I believe the intention is to merge as-is.

**Review by eike-hass — APPROVED** [review]

**Pull request merged**
