### PR TITLE
Update wiki DIDComm flowcharts, add banners

### PR DESCRIPTION
**Pull request by JSto91**
# Description of change
**Recolored and changed size (full width) the flowcharts from DIDCOMM Specs** 
This change also brings the draw.io library for Identity (colored elements) feel free to fork the repo and test it:
https://github.com/iota-wiki/Design-Resources/tree/main/flowchart_library

**Add new banners to pages:**
- Introduction
- Decentralized Identity
- Getting started overview

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
https://gitpod.io/#https://github.com/JSto91/identity.rs/tree/feat/update_flowchart_add_banner

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by eike-hass** [comment]
We also need to merge this into `support/v0.6` and `dev` branches

**Review by eike-hass — APPROVED** [review]
LGTM!

**Review by cycraig — COMMENTED** [review]
**Issuance diagram**: the branches of "Delegate Signing?" are incorrect.
- Left branch "Presentation" should be "Signing".
- Right branch "Resolve DID" should be "Sign verifiable credential".

**Signing diagram**: the names of the messages do not match.
- "signed-acknowledgement" should be "signing-acknowledgement".
- "receive signed-acknowledgement" should be "receive signing-acknowledgement".

The text is a bit small in general, but maybe it's just my eyes that find it difficult to read.

Otherwise I like the new colours and I'm able to load in the svg from draw.io, much appreciated.

Edit: the new banners are great.

**Comment by JSto91** [comment]
Sorry i really tried to double-check the flowchart but still missed something 😅 Fixed it. 

I mostly kept the original size of the components and enlarged the text only where it was barely visible + giving the content more space. Wasn't sure how far i can go.

**Comment by cycraig** [comment]
> I mostly kept the original size of the components and enlarged the text only where it was barely visible + giving the content more space.

Yeah I think it's just the extra spacing around everything making the text look smaller, the enlarged text on the lines is better than before though.

**Review by cycraig — APPROVED** [review]

**Comment by eike-hass** [comment]
@JSto91 can you please sing your commits? As soon as that is done we will merge the changes to all relevant branches.

**Comment by JSto91** [comment]
> @JSto91 can you please sign your commits? As soon as that is done we will merge the changes to all relevant branches.

Ok yeah @Dr-Electron will help me with that later 😅

**Pull request merged**
