### PR TITLE
Remove target caches in GitHub Actions

### PR DESCRIPTION
**Pull request by eike-hass**
# Description of change
Remove cargo target caches to decrease cache entries and size, hopefully increasing cache hits for the other caches.

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cycraig** [comment]
It looks like the caches are being restored, so I want to continue monitoring how often cache misses occur over one or two more days with the new examples workflow to see if this is still necessary (to reduce the size of our cache and help mitigate evictions leading to cache misses).

We also need to fix the currently failing CI builds before this can be evaluated properly, e.g. https://github.com/iotaledger/identity.rs/runs/3420522074?check_suite_focus=true

**Comment by cycraig** [comment]
I gathered the statistics of the last 23 build-and-test workflow runs over the past week. 

The results imply that cache misses are relatively infrequent, with only 5 misses out of 23 over the course of a week.
<table>
    <thead>
        <tr>
            <th></th>
            <th colspan=3>Cache Restore Hits</th>
        </tr>
       <tr>
            <th>OS</th>
            <th>Cargo</th>
            <th>Build Target</th>
            <th>sccache</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>ubuntu-latest</td>
            <td>23/23 (100%)</td>
            <td>18/23 (78%)</td>
            <td>21/23 (91%)</td>
        </tr>
        <tr>
            <td>macos-latest</td>
            <td>21/23 (91%)</td>
            <td>21/23 (91%)</td>
            <td>21/23 (91%)</td>
        </tr>
        <tr>
            <td>windows-latest</td>
            <td>21/23 (91%)</td>
            <td>21/23 (91%)</td>
            <td>18/23 (78%)</td>
        </tr>
    </tbody>
</table>

The timings also showcase the massive reduction in compilation time during GitHub Action runs, typically saving 6-9 minutes per run when the cache is restored successfully. I don't have hard statistics of the time reduction `sccache` gives us without the build target cache since every time the build target experienced a cache miss, so too did the `sccache` cache.
<table>
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th colspan=6>Timings (average seconds ± stdev.)</th>
        </tr>
       <tr>
            <th>OS</th>
            <th>Build Target</th>
            <th>Build</th>
            <th>Build & Run Tests</th>
            <th>Action Total</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=2>ubuntu-latest</td>
            <td>cached</td>
            <td>110 ± 147</td>
            <td>700 ± 88</td>
            <td>856 ± 200</td>
        </tr>
        <tr>
            <td>uncached</td>
            <td>457 ± 160</td>
            <td>740 ± 87</td>
            <td>1244 ± 210</td>
        </tr>
        <tr>
            <td rowspan=2>macos-latest</td>
            <td>cached</td>
            <td>133 ± 123</td>
            <td>687 ± 88</td>
            <td>1053 ± 330</td>
        </tr>
        <tr>
            <td>uncached</td>
            <td>439 ± 181</td>
            <td>687 ± 94</td>
            <td>1594 ± 359</td>
        </tr>
        <tr>
            <td rowspan=2>windows-latest</td>
            <td>cached</td>
            <td>196 ± 134</td>
            <td>828 ± 123</td>
            <td>1152 ± 275</td>
        </tr>
        <tr>
            <td>uncached</td>
            <td>481 ± 153</td>
            <td>920 ± 121</td>
            <td>1581 ± 279</td>
        </tr>
    </tbody>
</table>

Note in particular that the "Build & Run Tests" step takes significantly longer than "Build" alone. This is due to a recompilation step occurring to build the tests and examples, which sometimes takes, e.g. 13 minutes when the tests themselves run in a few seconds.

Given the above, I would suggest not removing the build target cache. If we experience an uptick in cache misses, we should start with removing the `sccache` cache steps first, as the impact of `sccache` feels less than the build target cache.

Lastly, I suggest altering the "Build" step cargo command to build the tests and examples too to save time by avoiding recompilation. This will make debugging failed builds slightly more difficult (as one would not be able to discern at a glance whether the build failed due to a test/example compilation or the source code itself), but reading the error logs themselves seems sufficient.

In my opinion this PR may be closed.

**Review by cycraig — COMMENTED** [review]
See above comment.

**Comment by eike-hass** [comment]
Due to the findings this change does not improve our cache efficiency.

**Pull request closed without merging**
