### PR TITLE
Pin axios version

### PR DESCRIPTION
**Pull request by eike-hass**
# Description of change
Please write a summary of your changes and why you made them.

## Links to any relevant issues
Be sure to reference any related issues by adding `fixes issue #`.

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
Describe the tests that you ran to verify your changes.
Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by cycraig — CHANGES_REQUESTED** [review]
Not sure if this is worth it honestly: `axios` is a transient dependency of `wasm-pack`, which is just a `dev-dependency` of ours, so the security warning should not affect users of the package (as far as I know).

Is there a way to avoid falsely marking `axios` as one of our dependencies? Because with this PR it would force all users of our package to download it too, if I understand correctly.

Something like what `wasm-pack` does with `resolutions`, or perhaps a `dev-dependency` rather?

https://github.com/rustwasm/wasm-pack/blob/4ae6306570a0011246c39c8028a4f11a4236f54b/npm/package.json#L36
```
"resolutions": {
  "axios": "0.21.2"
}
```

**Comment by eike-hass** [comment]
I agree that axios should not be shipped to users and this probably is the wrong approach.
We can flat out tell dependabot to ignore axios, but I think it does so no matter the dependency tree, so if we would add it later as an actual dependency it would still be ignored.
I fiddled around with overrides (https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides), but they don't seem to work for `devDependencies`. 
Should we maybe just keep the later as an reminder to update wasm-pack?

**Review by cycraig — CHANGES_REQUESTED** [review]
We still should not add unnecessary dependencies for developers installing the `identity-wasm` package, especially not to fix a dev-dependency security warning that does not affect them.

We should rather just address security warning by bumping `follow-redirects` to 1.14.8/1.14.9 which #656 did (which is essentially what this PR is meant to address).

We already have an open issue to upgrade wasm-pack when they next release a working version for Windows #608.

**Comment by eike-hass** [comment]
going with the original approach in https://github.com/iotaledger/identity.rs/pull/677

**Pull request closed without merging**
