### PR TITLE
Docs - fix imports in wiki

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

* Removed comment about txm which causes a compilation error upon importing from the wiki

## Type of change

- [x] Bug fix (a non-breaking change which fixes an issue)
- [x] Documentation Fix

## How the change has been tested

Changes were tested locally and deployed at https://lucas-tortora.github.io/iota-wiki/identity.rs/libraries/wasm/getting_started

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by lucas-tortora** [comment]
@iotaledger/tech-writers , could someone review this please?

**Comment by cycraig** [comment]
The comment is actually functional: it uses [`txm`](https://github.com/anko/txm) to run code example in Markdown files. However, if it's causing problems with the wiki then removing it is acceptable.

**Comment by lucas-tortora** [comment]
> The comment is actually functional: it uses [`txm`](https://github.com/anko/txm) to run code example in Markdown files. However, if it's causing problems with the wiki then removing it is acceptable.

Thanks for the feedback ! If you think it's OK, we can remove it for now while we work on a solution to keep it.

**Review by cycraig — APPROVED** [review]
Agreed, removing this is fine for now. We'll look for an alternative Markdown example runner on our side too.

**Pull request merged**
