### PR TITLE
Upgrade webpack and libs

### PR DESCRIPTION
**Pull request by eike-hass**
# Description of change
Upgrade webpack and related libraries to the latest version. Takes care security warnings:
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/node-forge/open

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
Ran the build and tests examples locally.

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by cycraig — COMMENTED** [review]
~~I don't have permission to view any security advisories on GitHub.~~ 

Edit: I now have access, thank you.

**Review by cycraig — CHANGES_REQUESTED** [review]
After a clean `npm i`, `wasm-pack` is broken for me. Not sure if that's just my side since I went back to dev and it's still broken. Which I think is because of #621?

`npm run build && npm run build:examples && npm run test:unit`

Error log:
```
> @iota/identity-wasm@0.5.0-dev.3 build
> npm run build:web && npm run build:nodejs && npm run build:docs


> @iota/identity-wasm@0.5.0-dev.3 build:web
> wasm-pack build --target web --release --out-dir web && node ./build/web

Error: spawnSync C:\Work\iota\identity.rs\bindings\wasm\node_modules\binary-install\bin\wasm-pack.exe UNKNOWN
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:812:24)
    at Binary.run (C:\Work\iota\identity.rs\bindings\wasm\node_modules\binary-install\index.js:84:20)
    at run (C:\Work\iota\identity.rs\bindings\wasm\node_modules\wasm-pack\binary.js:34:10)
    at Object.<anonymous> (C:\Work\iota\identity.rs\bindings\wasm\node_modules\wasm-pack\run.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawnSync C:\\Work\\iota\\identity.rs\\bindings\\wasm\\node_modules\\binary-install\\bin\\wasm-pack.exe',
  path: 'C:\\Work\\iota\\identity.rs\\bindings\\wasm\\node_modules\\binary-install\\bin\\wasm-pack.exe',
  spawnargs: [ 'build', '--target', 'web', '--release', '--out-dir', 'web' ]
}                                     
```

**Comment by eike-hass** [comment]
should be fine after #629

**Review by cycraig — APPROVED** [review]
Seems fine now, Wasm tests and examples pass my side. Thank you.

**Pull request merged**
