### PR TITLE
Use own docker image for changelog generator

### PR DESCRIPTION
**Pull request by eike-hass**
# Description of change
Use our own image with the latest revision from https://github.com/github-changelog-generator/github-changelog-generator to get necessary bugfixes.

## Type of change
Add an `x` to the boxes that are relevant to your changes.

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [X] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Fix

## How the change has been tested
The change has already been on the support branch https://github.com/iotaledger/identity.rs/actions/runs/1683399961

## Change checklist
Add an `x` to the boxes that are relevant to your changes.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cycraig** [comment]
Given that the [Dockerfile commands](https://github.com/eike-hass/docker-github-changelog-generator/blob/master/Dockerfile) are relatively simple, could we instead install the github-changelog-generator gem inside the GitHub Actions pipeline directly rather than using Docker? Does it take a significant amount of time to install or are there other concerns running it outside of Docker?

**Comment by eike-hass** [comment]
> Given that the [Dockerfile commands](https://github.com/eike-hass/docker-github-changelog-generator/blob/master/Dockerfile) are relatively simple, could we instead install the github-changelog-generator gem inside the GitHub Actions pipeline directly rather than using Docker? Does it take a significant amount of time to install or are there other concerns running it outside of Docker?
> 
> E.g.
> 
> ```
> - name: Set up Ruby (assuming this is necessary to use gem)
>   uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
>   with:
>     ruby-version: 2.6
> 
> - name: Install github-changelog-generator
>   run: |
>     REPO="https://github.com/github-changelog-generator/github-changelog-generator.git"
>     REF=594a9ccbf84a3172d05d35bb88a0998ed4a948a0
>     gem install specific_install
>     gem specific_install -l ${REPO} -r ${REF}
> ```
> 
> Then alter the run command to call `github-changelog-generator` directly?

Not a fan of having ruby installed in our pipeline TBH. I think Docker abstracts the underlying runtime away nicely and there is an official image we can migrate to once updated which has a blessed setup and pipeline. Speedwise it might be more the or less same I would assume.

**Comment by cycraig** [comment]
It removes an external dependency on your repository/DockerHub account and in my mind makes it simpler to change the pinned revision if need be without publishing a new Docker image (which will always depend on you as it stands).

I'm alright with the Docker container as a temporary fix, just thinking a year or two down the line when everyone has forgotten about this and it needs updating.

**Comment by eike-hass** [comment]
> It removes an external dependency on your GitHub/DockerHub accounts and in my mind makes it simpler to change the pinned revision if need be without publishing a new Docker image (which will always depend on you as it stands).
> 
> I'm alright with the custom Docker image as a temporary fix, just thinking a year or two down the line when everyone has forgotten about this and it needs updating.

Absolutely agree that this must not be a permanent setup. I pinged the guys at the original repo when we can expect an official release and I would like to migrate to that ASAP, which then would be as easy as changing the image.

**Review by cycraig — APPROVED** [review]

**Pull request merged**
